//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int InfoID { get; set; }
        public int NodeID { get; set; }
        public short TreeID { get; set; }
        public short TypeID { get; set; }
        public string Heading { get; set; }
        public string InfoText { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Tree Tree { get; set; }
        public virtual Typ Type { get; set; }
    }
}
