//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Infoes = new HashSet<Info>();
            this.Keys = new HashSet<Key>();
            this.Notes = new HashSet<Note>();
            this.Pictures = new HashSet<Picture>();
            this.Summaries = new HashSet<Summary>();
        }
    
        public int NodeID { get; set; }
        public short TreeID { get; set; }
        public short TypeID { get; set; }
        public int ParentNodeID { get; set; }
        public short TreeLevel { get; set; }
        public string Heading { get; set; }
        public string NodeText { get; set; }
    
        public virtual ICollection<Info> Infoes { get; set; }
        public virtual ICollection<Key> Keys { get; set; }
        public virtual Tree Tree { get; set; }
        public virtual Typ Type { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Summary> Summaries { get; set; }
    }
}
