//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        public Tree()
        {
            this.Infoes = new HashSet<Info>();
            this.Keys = new HashSet<Key>();
            this.Nodes = new HashSet<Node>();
        }
    
        public short TreeID { get; set; }
        public string Heading { get; set; }
        public short TypeID { get; set; }
    
        public virtual ICollection<Info> Infoes { get; set; }
        public virtual ICollection<Key> Keys { get; set; }
        public virtual ICollection<Node> Nodes { get; set; }
        public virtual Typ Type { get; set; }
    }
}
